# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 245e26a2f885cf09d540362c27a9b7c10d712f9d3c6b00f7e54d12555ff9860e6040558d60ec9e6345a305cc592bdd2f388e1e0163f5eacdf4df484d76c1c2b5

test:
  secret_key_base: 2dc581e9efd37f18784e445e8327744a9df53dd4deefa337128fa15738b434522f9aea319a1b1b94329eba95d9b8bf845246040d87d3b2e12e28be59afb5bc41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
